services:
  api:
    build: .
    ports:
      - "8083:8083"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    restart: always
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8083 --reload

  mysql:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "3311:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./iris_db_dump.sql:/docker-entrypoint-initdb.d/iris_db_dump.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - default

networks:
  default:
  sleeved-network:
    external: true

volumes:
  db_data:
