version: "3"

services:
  api:
    build: .
    ports:
      - "8083:8083"
    env_file:
      - .env
    depends_on:
      - mysql
    restart: always
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8083 --reload
    networks:
      - default
      - sleeved-network
    container_name: iris-api

  mysql:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "3311:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default

networks:
  default:
  sleeved-network:
    external: true

volumes:
  mysql_data:
