version: '3'

tasks:
  build:
    desc: Build the Docker containers
    cmds:
      - docker-compose build --no-cache

  start:
    desc: Start the application
    cmds:
      - docker-compose up -d

  stop:
    desc: Stop the application
    cmds:
      - docker-compose down

  logs:
    desc: View logs
    cmds:
      - docker-compose logs -f

  lint:
    desc: Run linting checks
    cmds:
      - docker-compose exec api flake8 .

  format:
    desc: Format the code with black
    cmds:
      - docker-compose exec api black .

  # Apply test command when we have setstart tests
  # test:
  #   desc: Run tests
  #   cmds:
  #     - docker-compose exec api pytest

  shell:
    desc: Open a shell in the API container
    cmds:
      - docker-compose exec api bash

  restart:
    desc: Restart the application
    cmds:
      - task: stop
      - task: start
      - task: logs

  rebuild:
    desc: Rebuild and restart
    cmds:
      - task: stop
      - task: build
      - task: start
      - task: logs

  setup-hooks:
      desc: Set up Git hooks without local dependencies
      cmds:
        - mkdir -p .git/hooks
        - cp scripts/pre-commit.sh .git/hooks/pre-commit
        - chmod +x .git/hooks/pre-commit
        - echo "✅ Git hooks installed successfully! No pip install needed."