"""create card hash table

Revision ID: e03299a3d603
Revises:
Create Date: 2025-06-04 12:20:13.536554

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e03299a3d603"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "card_hash",
        sa.Column(
            "id",
            sa.String(length=255),
            nullable=False,
            comment="Unique card identifier",
        ),
        sa.Column(
            "hash",
            sa.String(length=128),
            nullable=False,
            comment="Perceptual hash of the card image",
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_hash_prefix",
        "card_hash",
        ["hash"],
        unique=False,
        mysql_length=64,
        postgresql_ops={"hash": "varchar_pattern_ops"},
    )
    op.create_index(op.f("ix_card_hash_hash"), "card_hash", ["hash"], unique=False)
    op.create_index(op.f("ix_card_hash_id"), "card_hash", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_card_hash_id"), table_name="card_hash")
    op.drop_index(op.f("ix_card_hash_hash"), table_name="card_hash")
    op.drop_index(
        "idx_hash_prefix",
        table_name="card_hash",
        mysql_length=64,
        postgresql_ops={"hash": "varchar_pattern_ops"},
    )
    op.drop_table("card_hash")
    # ### end Alembic commands ###
